version: "3"
services:
  chromedp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: chromedp_docker
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 6000M
    environment:
      - TYPE=chromedp
  selenium:
    build:
      context: ./
      dockerfile: selenium/Dockerfile
    image: selenium_docker
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 6000M
    environment:
      - TYPE=selenium